//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Ban_Quan_Ao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUAN_TRI
    {
        public string Tai_khoan { get; set; }
        public string Mat_khau { get; set; }
        public string So_dien_thoai { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
    }
}
